server:
  servlet:
    context-path: /todo
spring:
  application:
    name: todo-list
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
springdoc:
  swagger-ui:
    operationsSorter: method