CREATE TABLE todo_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    description TEXT NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'NOT_DONE',
    due_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    done_at DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
